// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using axiosTest.Models;

#nullable disable

namespace axiosTest.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20250928062210_oracleDbMigration")]
    partial class oracleDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("axiosTest.Models.FormInfo", b =>
                {
                    b.Property<int>("FormInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormInfoId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<TimeSpan>("CreatedTime")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<int>("Creator")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FormNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("FormInfoId");

                    b.ToTable("FormInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
